server:
  port: 9999
spring:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
          ddl-auto: update

  #datasource:
    #url: jdbc:mysql://localhost:3306/db_house
    #username: root
    #password: root

  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_house?characterEncoding=UTF-8
    username: root
    password: root


